import "../globals.css";
import Navbar from "../components/shared/Navbar/Navbar";
import Footer from "../components/shared/Footer/Footer";
import Providers from "@/app/provider/provider"; 
import { Toaster } from 'react-hot-toast';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <Providers> 
      <html lang="en">
        <body>
          <Navbar />
          {children}
          <Toaster />
          <Footer />
        </body>
      </html>
    </Providers>
  );
}
